Update pull_request_template.md
nymedia/.github pull request #4
Opened 2021-11-23 12:44 UTC by eiriksm

2021-11-23 13:30 UTC, zaporylie requested changes

2021-11-23 13:30 UTC, zaporylie commented on pull_request_template.md
> +### Are all code, documentation, and commits are in English?
Are (....) are in English?

2021-11-23 15:04 UTC, eiriksm commented on pull_request_template.md
> +### Are all code, documentation, and commits are in English?
Are are are are... English?

2022-11-09 14:54 UTC, esolitos commented
I like this idea of multiple answers!

2022-11-10 11:14 UTC, eiriksm commented
Huh totally forgot about this.

I think the thought was we wanted it to be a checklist instead. So someone not checking all boxes means they did not read or did not actually complete the PR.

2022-11-10 11:40 UTC, esolitos commented
The downside of the checklist is that people then just check'em all without thinking pretty soon, here instead at least one needs to aim for the correct one. :D 

The best would be radio, but that ain't supported out of the box.

--
⚠️ _Scope creep incoming_

The *even better solution* imho would be a bot which adds a comment in the PR whit those questions and uses labels to identify the PRs based on the answers. :)

2022-11-14 11:59 UTC, eiriksm commented
```
// @todo
```

2025-04-29 17:42 UTC, closed without merging